kind: Namespace
apiVersion: v1
metadata:
  name: gateway
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: gateway
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gateway-pvc
  namespace: gateway
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
spec:
  replicas: 1 # cannot be really scaled because of local backend
  template:
    metadata:
      namespace: gateway
      labels:
        app: gateway
    spec:
      initContainers:
      - name: gateway-init
        image: epik-protocol/gateway:v0.1.0
        command:
        - gateway
        - init
        - -c=/etc/epikgateway.json
        volumeMounts:
        - mountPath: /data
          name: database
      containers:
      - name: gateway
        image: epik-protocol/gateway:v0.1.0
        command:
        - gateway
        - http
        - --init # TODO: remove once initContainers is out of beta
        - -c=/etc/epikgateway.json
        - --host=:64210
        ports:
        - name: http
          containerPort: 64210
        volumeMounts:
        - mountPath: /data
          name: database
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: gateway-pvc
