kind: Namespace
apiVersion: v1
metadata:
  name: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: gateway
  labels:
    name: mongo
spec:
  ports:
  - name: mgo
    port: 27017
    targetPort: mgo
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: gateway
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      namespace: gateway
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - name: mgo
              containerPort: 27017
          volumeMounts:
            - name: mongo-pvc
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 20Gi
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: gateway
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
spec:
  replicas: 1
  template:
    metadata:
      namespace: gateway
      labels:
        app: gateway
    spec:
      initContainers:
      - name: gateway-init
        image: epik-protocol/gateway:v0.1.0
        command:
        - gateway
        - init
        - -d=mongo
        - -a=mongo
      containers:
      - name: gateway
        image: epik-protocol/gateway:v0.1.0
        command:
        - gateway
        - http
        - --init # TODO: remove once initContainers works properly
        - -d=mongo
        - -a=mongo
        - --host=:64210
        ports:
        - name: http
          containerPort: 64210